// packages/angular/src/blocks/code-block.component.ts
import { Component, Input } from "@angular/core";
import type { CodeBlock } from "aidk-client";

@Component({
  selector: "aidk-code-block",
  standalone: true,
  template: `
    <div>
      @if (block.language) {
        <div style="font-size: 0.75rem; color: #666; margin-bottom: 4px; font-family: monospace;">
          {{ block.language }}
        </div>
      }
      <pre style="background-color: #1e1e1e; color: #d4d4d4; padding: 12px; border-radius: 4px; overflow: auto; font-size: 0.875rem; margin: 0;">
        <code>{{ block.text }}</code>
      </pre>
    </div>
  `,
})
export class CodeBlockComponent {
  @Input() block!: CodeBlock;
}

// packages/react/src/blocks/CodeBlock.tsx
import type { CodeBlock as CodeBlockType } from 'aidk-client';

interface Props {
  block: CodeBlockType;
  className?: string;
}

export function CodeBlock({ block, className }: Props) {
  return (
    <div className={className}>
      {block.language && (
        <div
          style={{
            fontSize: '0.75rem',
            color: '#666',
            marginBottom: '4px',
            fontFamily: 'monospace',
          }}
        >
          {block.language}
        </div>
      )}
      <pre
        style={{
          backgroundColor: '#1e1e1e',
          color: '#d4d4d4',
          padding: '12px',
          borderRadius: '4px',
          overflow: 'auto',
          fontSize: '0.875rem',
          margin: 0,
        }}
      >
        <code>{block.text}</code>
      </pre>
    </div>
  );
}
