// packages/angular/src/blocks/image-block.component.ts
import { Component, Input } from '@angular/core';
import type { GeneratedImageBlock, ImageBlock } from 'aidk-client';

@Component({
  selector: 'aidk-image-block',
  standalone: true,
  template: `
    @if (src) {
      <img [src]="src" [alt]="block.alt_text || 'Image'" style="max-width: 100%; height: auto; border-radius: 4px;" />
    } @else {
      <div>[Image: unsupported source type]</div>
    }
  `,
})
export class ImageBlockComponent {
  @Input() block!: ImageBlock | GeneratedImageBlock;

  get src(): string | undefined {
    if (this.block.type === 'generated_image') {
      return this.block.data;
    }
    if (this.block.source.type === 'url') {
      return this.block.source.url;
    }
    if (this.block.source.type === 'base64') {
      const mimeType = this.block.mime_type || 'image/png';
      return `data:${mimeType};base64,${this.block.source.data}`;
    }
    return undefined;
  }
}

// packages/react/src/blocks/ImageBlock.tsx
import type { GeneratedImageBlock, ImageBlock as ImageBlockType } from 'aidk-client';

interface Props {
  block: ImageBlockType | GeneratedImageBlock;
  className?: string;
}

export function ImageBlock({ block, className }: Props) {
  let src: string | undefined;
  
  if (block.type === 'generated_image') {
    src = block.data;
  } else {
    if (block.source.type === 'url') {
      src = block.source.url;
    } else if (block.source.type === 'base64') {
      const mimeType = block.mime_type || 'image/png';
      src = `data:${mimeType};base64,${block.source.data}`;
    }
  }

  if (!src) {
    return <div className={className}>[Image: unsupported source type]</div>;
  }

  return (
    <img
      src={src}
      alt={block.alt_text || 'Image'}
      className={className}
      style={{ maxWidth: '100%', height: 'auto', borderRadius: '4px' }}
    />
  );
}
