// packages/angular/src/blocks/tool-use-block.component.ts
import { Component, Input } from '@angular/core';
import type { ToolUseBlock } from 'aidk-client';

@Component({
  selector: 'aidk-tool-use-block',
  standalone: true,
  template: `
    <div style="display: flex; align-items: center; gap: 6px; padding: 4px 8px; background-color: #f0f0f0; border-radius: 4px; font-size: 0.875rem; color: #555;">
      <span>🔧</span>
      <span style="font-weight: 500;">{{ block.name }}</span>
      <span style="color: #888;">— {{ inputSummary }}</span>
      @if (block.toolResult) {
        <span style="display: flex; flex: 1; justify-content: flex-end;">{{ block.toolResult.isError ? '❌' : '✅' }}</span>
      } @else {
        <span style="display: flex; flex: 1; justify-content: flex-end;">⏳</span>
      }
    </div>
  `,
})
export class ToolUseBlockComponent {
  @Input() block!: ToolUseBlock;

  get inputSummary(): string {
    const keys = Object.keys(this.block.input || {});
    return keys.length > 0 
      ? `${keys.length} field${keys.length > 1 ? 's' : ''}`
      : 'no input';
  }
}

// packages/react/src/blocks/ToolUseBlock.tsx
import type { ToolUseBlock as ToolUseBlockType } from "aidk-client";

interface Props {
  block: ToolUseBlockType;
  className?: string;
}

export function ToolUseBlock({ block, className }: Props) {
  const inputKeys = Object.keys(block.input || {});
  const inputSummary =
    inputKeys.length > 0
      ? `${inputKeys.length} field${inputKeys.length > 1 ? "s" : ""}`
      : "no input";

  return (
    <div
      className={className}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        padding: "4px 8px",
        backgroundColor: "#f0f0f0",
        borderRadius: "4px",
        fontSize: "0.875rem",
        color: "#555",
      }}
    >
      <span>🔧</span>
      <span style={{ fontWeight: 500 }}>{block.name}</span>
      <span style={{ color: "#888" }}>— {inputSummary}</span>
      {block.toolResult ? (
        <span style={{ display: "flex", flex: 1, justifyContent: "flex-end" }}>
          {block.toolResult.isError ? "❌" : "✅"}
        </span>
      ) : (
        <span style={{ display: "flex", flex: 1, justifyContent: "flex-end" }}>⏳</span>
      )}
    </div>
  );
}
